import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import Anthropic from "@anthropic-ai/sdk";
import { GoogleGenAI, Type } from "@google/genai";
import dotenv from "dotenv";

dotenv.config();

const app = express();
const PORT = 3000;

app.use(express.json());

// Helper to call Anthropic API with retry and fallback model in case of transient 503/429 errors
async function generateContentWithRetry(client: Anthropic, contents: string, systemPrompt: string, toolSchema: any) {
  const modelsToTry = [
    "claude-3-5-sonnet-20241022",
    "claude-3-5-sonnet-20240620",
    "claude-3-5-sonnet-latest",
    "claude-3-5-haiku-20241022",
    "claude-3-haiku-20240307",
    "claude-3-7-sonnet-latest",
    "claude-3-7-sonnet-20250219",
    "claude-3-opus-20240229"
  ];
  let lastError: any = null;

  for (const model of modelsToTry) {
    let retries = 2; // Try up to 3 times per model
    let delay = 1000;

    while (retries >= 0) {
      try {
        console.log(`[Anthropic SDK] Trying messages.create with model: ${model} (${retries} retries remaining)`);
        const response = await client.messages.create({
          model: model,
          max_tokens: 4000,
          system: systemPrompt,
          messages: [{ role: "user", content: contents }],
          tools: [{
            name: "output_goal_plan",
            description: "Decomposes user raw goals into a structured daily plan or follow-up question.",
            input_schema: toolSchema
          }],
          tool_choice: { type: "tool", name: "output_goal_plan" }
        });
        
        // Find the tool_use content block
        const toolUseBlock = response.content.find((block: any) => block.type === "tool_use") as any;
        if (toolUseBlock && toolUseBlock.input) {
          return toolUseBlock.input;
        }
        
        throw new Error("No tool_use block was generated by Claude.");
      } catch (err: any) {
        lastError = err;
        const errMsg = err?.message || String(err);
        const errStatus = err?.status || err?.code;
        
        console.log(`[Anthropic SDK] Muted Warning: Error with model ${model}: status=${errStatus}, msg=${errMsg}`);
        
        const isClientError =
          errStatus === 400 ||
          errStatus === 401 ||
          errStatus === 403 ||
          errStatus === 404 ||
          errMsg.includes("not_found_error") ||
          errMsg.includes("invalid_request_error") ||
          errMsg.includes("authentication_error") ||
          errMsg.includes("permission_error");

        if (isClientError) {
          console.log(`[Anthropic SDK] Permanent client/access error detected (status=${errStatus}). Fail-fast triggered to prevent retry latency.`);
          throw err;
        }

        const isTransient = 
          errStatus === 503 || 
          errStatus === 429 || 
          errStatus === 504 ||
          errStatus === 502 ||
          errMsg.includes("503") || 
          errMsg.includes("429") || 
          errMsg.includes("504") ||
          errMsg.includes("Overloaded") ||
          errMsg.includes("rate limit") ||
          errMsg.includes("temporary") ||
          errMsg.includes("Resource has been exhausted");
          
        if (isTransient && retries > 0) {
          const jitter = Math.floor(Math.random() * 200) + 50;
          const waitTime = delay + jitter;
          console.log(`[Anthropic SDK] Transient error detected. Retrying in ${waitTime}ms (delay: ${delay}ms)...`);
          await new Promise((resolve) => setTimeout(resolve, waitTime));
          delay *= 1.5;
          retries--;
        } else {
          break;
        }
      }
    }
  }

  throw lastError;
}

// Helper to call Gemini SDK with retry
async function generateContentWithGemini(ai: any, contents: string, systemPrompt: string, responseSchema: any) {
  const modelsToTry = ["gemini-3.5-flash", "gemini-3.1-flash-lite", "gemini-flash-latest"];
  let lastError: any = null;

  for (const model of modelsToTry) {
    let retries = 1; // Try up to 2 times per model
    let delay = 500;

    while (retries >= 0) {
      try {
        console.log(`[Gemini SDK] Trying generateContent with model: ${model} (${retries} retries remaining)`);
        const response = await ai.models.generateContent({
          model: model,
          contents: contents,
          config: {
            systemInstruction: systemPrompt,
            responseMimeType: "application/json",
            responseSchema: responseSchema,
          },
        });
        
        if (response && response.text) {
          return JSON.parse(response.text);
        }
        throw new Error("Empty response received from Gemini.");
      } catch (err: any) {
        lastError = err;
        const errMsg = err?.message || String(err);
        const errStatus = err?.status || err?.code;
        
        console.log(`[Gemini SDK] Muted Warning: Error with model ${model}: status=${errStatus}, msg=${errMsg}`);
        
        const isTransient = 
          errStatus === 503 || 
          errStatus === 429 || 
          errStatus === 504 ||
          errStatus === 502 ||
          errMsg.includes("503") || 
          errMsg.includes("429") || 
          errMsg.includes("504") ||
          errMsg.includes("UNAVAILABLE") || 
          errMsg.includes("high demand") || 
          errMsg.includes("temporary") ||
          errMsg.includes("Resource has been exhausted");
          
        if (isTransient && retries > 0) {
          const jitter = Math.floor(Math.random() * 150) + 50;
          const waitTime = delay + jitter;
          console.log(`[Gemini SDK] Transient error detected. Retrying in ${waitTime}ms (delay: ${delay}ms)...`);
          await new Promise((resolve) => setTimeout(resolve, waitTime));
          delay *= 1.5;
          retries--;
        } else {
          break;
        }
      }
    }
  }

  throw lastError;
}

// Initialize Gemini SDK with telemetry header
const getGeminiClient = () => {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    console.log("Info: GEMINI_API_KEY environment variable is missing in setup.");
  }
  return new GoogleGenAI({
    apiKey: apiKey || "dummy-key",
    httpOptions: {
      headers: {
        'User-Agent': 'aistudio-build',
      }
    }
  });
};

// Initialize Anthropic SDK
const getAnthropicClient = () => {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) {
    console.log("Info: ANTHROPIC_API_KEY environment variable is missing in setup.");
  }
  return new Anthropic({
    apiKey: apiKey || "dummy-key",
  });
};

// Localized fallback plan heuristic engine to ensure zero downtime when external LLM access is temporarily saturated
function getHeuristicFallbackPlan(msg: string): any {
  const message = (msg || "").toLowerCase();
  
  if (message.includes("meditat") || message.includes("mind") || message.includes("calm") || message.includes("zen") || message.includes("breath") || message.includes("relax")) {
    return {
      needsClarification: false,
      goalPlan: {
        normalizedObjective: "Daily Mindful Practice",
        description: "Focus on breath control, sensory calm, and mindful stretches to build solid daily awareness cycles.",
        category: "Wellness",
        targetValue: 10,
        unit: "mins",
        frequency: "daily",
        isRecurring: true,
        recurringDays: ["Mon", "Wed", "Fri", "Sat", "Sun"],
        color: "emerald",
        icon: "Heart",
        tasks: [
          { title: "Find a quiet space & take 10 deep diaphragmatic breaths", dayIndex: 0, value: 1 },
          { title: "Spend 5 minutes observing background sounds without judgment", dayIndex: 1, value: 5 },
          { title: "Complete a 10-minute seated silent self-awareness cycle", dayIndex: 2, value: 10 },
          { title: "Perform a gentle 3-minute conscious stretch routine during work", dayIndex: 3, value: 3 },
          { title: "Log active stress points and decompress offline before modern sleep", dayIndex: 4, value: 5 },
          { title: "Practice a simple 8-minute relaxing breathwork template", dayIndex: 5, value: 10 },
          { title: "Verify weekly serenity scores and award yourself mental calm", dayIndex: 6, value: 1 }
        ]
      }
    };
  }
  
  if (message.includes("code") || message.includes("python") || message.includes("java") || message.includes("dev") || message.includes("program") || message.includes("learn") || message.includes("study")) {
    return {
      needsClarification: false,
      goalPlan: {
        normalizedObjective: "Incremental Skills Development",
        description: "Establish strong developer study habits, micro-scripts coding, and logical thinking structures.",
        category: "Learning",
        targetValue: 30,
        unit: "mins",
        frequency: "daily",
        isRecurring: true,
        recurringDays: ["Mon", "Tue", "Wed", "Thu", "Fri"],
        color: "indigo",
        icon: "Code",
        tasks: [
          { title: "Build folder layout, configure workspace & write Hello World", dayIndex: 0, value: 1 },
          { title: "Spend 15 minutes exploring basic primitive types and structures", dayIndex: 1, value: 15 },
          { title: "Construct three conditional statements and execute custom checks", dayIndex: 2, value: 10 },
          { title: "Decompose a small utility program idea into separate functions", dayIndex: 3, value: 5 },
          { title: "Implement a basic loop structure that prints item variables", dayIndex: 4, value: 15 },
          { title: "Experiment with adding clean logs or error handlers for 20 mins", dayIndex: 5, value: 20 },
          { title: "Synthesize program structure and map incoming week's code study", dayIndex: 6, value: 1 }
        ]
      }
    };
  }

  if (message.includes("read") || message.includes("book") || message.includes("pages") || message.includes("novel")) {
    return {
      needsClarification: false,
      goalPlan: {
        normalizedObjective: "Daily Reading Habit Tracker",
        description: "Maintain a steady intellectual reading momentum while cutting away distracting screen time.",
        category: "Learning",
        targetValue: 10,
        unit: "pages",
        frequency: "daily",
        isRecurring: true,
        recurringDays: ["Mon", "Wed", "Fri", "Sat", "Sun"],
        color: "violet",
        icon: "BookOpen",
        tasks: [
          { title: "Pick a high-quality physical book and dedicate a reading spot", dayIndex: 0, value: 1 },
          { title: "Read precisely 5 pages without checking digital notifications", dayIndex: 1, value: 5 },
          { title: "Read 8 pages and write down one powerful paragraph or lesson", dayIndex: 2, value: 8 },
          { title: "Level up reading stamina to 10 full pages in quiet relaxation", dayIndex: 3, value: 10 },
          { title: "Deconstruct your favorite argument or character choice so far", dayIndex: 4, value: 10 },
          { title: "Discuss your active takeaways out loud with a family member", dayIndex: 5, value: 1 },
          { title: "Log your accumulated counts and choose the incoming chapter", dayIndex: 6, value: 1 }
        ]
      }
    };
  }

  if (message.includes("run") || message.includes("walk") || message.includes("exercise") || message.includes("gym") || message.includes("fit") || message.includes("workout")) {
    return {
      needsClarification: false,
      goalPlan: {
        normalizedObjective: "Daily Cardio & Mobility Challenge",
        description: "Get physical with lightweight cardiovascular routes, posture correction, and body mobility workouts.",
        category: "Fitness",
        targetValue: 15,
        unit: "mins",
        frequency: "daily",
        isRecurring: true,
        recurringDays: ["Mon", "Tue", "Thu", "Fri", "Sat"],
        color: "rose",
        icon: "Target",
        tasks: [
          { title: "Put on comfortable walking shoes & do a quick 5-min walk", dayIndex: 0, value: 5 },
          { title: "Perform 5 minutes of restorative joint and full body stretching", dayIndex: 1, value: 5 },
          { title: "Start a comfortable low-stamina workout or jog for 10 minutes", dayIndex: 2, value: 10 },
          { title: "Spend 12 minutes in movement and track your active heartbeat", dayIndex: 3, value: 12 },
          { title: "Add 5 simple bodyweight squats and pushups to build strength", dayIndex: 4, value: 5 },
          { title: "Map out a scenic green route in your neighborhood for 15 minutes", dayIndex: 5, value: 15 },
          { title: "Cool down with high-quality breathing cycles and log progress", dayIndex: 6, value: 1 }
        ]
      }
    };
  }

  // General default fallback plan
  return {
    needsClarification: false,
    goalPlan: {
      normalizedObjective: "Incremental Progress Builder",
      description: "Deconstruct a generalized habit change into bulletproof step-by-step milestones.",
      category: "Productivity",
      targetValue: 1,
      unit: "session",
      frequency: "daily",
      isRecurring: true,
      recurringDays: ["Mon", "Wed", "Fri"],
      color: "amber",
      icon: "Trophy",
      tasks: [
        { title: "Identify daily trigger times and complete a simple 2-minute action", dayIndex: 0, value: 1 },
        { title: "Work in a quiet workspace without multitasking loops for 5 minutes", dayIndex: 1, value: 1 },
        { title: "Identify one environment friction point and clear it off", dayIndex: 2, value: 1 },
        { title: "Double-down with an engaging focus segment of 10 solid minutes", dayIndex: 3, value: 1 },
        { title: "Write a sticky motivation draft and place it on your table", dayIndex: 4, value: 1 },
        { title: "Execute your target action cleanly and note physical momentum", dayIndex: 5, value: 1 },
        { title: "Audit your weekly completion streak and reward your focus", dayIndex: 6, value: 1 }
      ]
    }
  };
}

// API endpoint to decompose users raw text goals to daily checklist milestones
app.post("/api/coach/decompose", async (req, res) => {
  const { message, history } = req.body;
  
  if (!message) {
    return res.status(400).json({ error: "Goal message expression is required." });
  }

  const anthropicApiKey = process.env.ANTHROPIC_API_KEY;
  const hasAnthropicKey = anthropicApiKey && anthropicApiKey !== "MY_ANTHROPIC_API_KEY";
  const geminiApiKey = process.env.GEMINI_API_KEY;
  const hasGeminiKey = geminiApiKey && geminiApiKey !== "MY_GEMINI_API_KEY";

  // Reconstruct the message log for context awareness
  const dialogHistory = history && Array.isArray(history) 
    ? history.map((h: any) => `${h.role === 'user' ? 'User' : 'Coach'}: ${h.text}`).join("\n")
    : "";

  const systemPrompt = `You are Tracktion's premium AI Goal Coach and Decomposition Engine. Your job is to help users translate their vague, messy, or casual goals (e.g. 'i wanna code more', 'read things') into realistic, ultra-actionable daily roadmap plans.

Guidelines:
1. Examine the user's input. Check if the goal/current request is too vague, missing core details, or has no frequency / action metrics.
2. If it's too vague and you need more details to formulate a realistic 7-day path, set needsClarification=true and ask a friendly, supportive follow-up question. Keep your question concise (max 2 sentences) and highly encouraging.
3. If it is clear enough, decompose it into a full structured goal plan with needsClarification=false:
   - normalizedObjective: Title representing the habit/goal (e.g. '30-Min Daily Python Study' or '10,000 Step Afternoon Walk'). Keep it action-oriented.
   - description: A beautiful, brief, motivational overview description.
   - category: Must be one of: 'Wellness', 'Learning', 'Productivity', 'Fitness', 'Work', 'Creative', 'Health', 'Others'.
   - targetValue: Daily progress target number (e.g. 15, 30, 1, 2, 8).
   - unit: Unit of measurement (e.g. 'mins', 'pages', 'times', 'miles', 'lessons', 'cups').
   - frequency: 'daily' or 'weekly'.
   - isRecurring: true or false (true if they should repeat it across multiple days).
   - recurringDays: If isRecurring is true, select 2 to 5 short day labels that fit their schedule (e.g., ['Mon', 'Wed', 'Fri'] or ['Tue', 'Thu', 'Sat']).
   - color: Pick a color scheme matches the category: 'indigo', 'emerald', 'rose', 'amber', 'violet', 'sky'.
   - icon: One of: 'Heart', 'Trophy', 'BookOpen', 'Target', 'Calendar', 'Sparkles', 'Flame', 'CheckCircle2', 'Apple', 'Briefcase', 'GraduationCap', 'Code'.
   - tasks: An array of exactly 7 small tasks, representing tiny daily incremental tasks for each day from Day 1 to Day 7. Each task must map to a unique dayIndex from 0 (Day 1) to 6 (Day 7). Make sure the tasks are structured, ultra-easy, and linear to build strong momentum!`;

  const chatInput = `${dialogHistory ? `Conversation History So Far:\n${dialogHistory}\n\n` : ""}Current User Goal/Response: "${message}"`;

  // Always try Google Gemini SDK first as the native, robust, and free-to-use pathway in Google AI Studio
  if (hasGeminiKey) {
    try {
      console.log("[AI Goal Coach] Executing native primary route via Google GenAI SDK...");
      const ai = getGeminiClient();

      const geminiResponseSchema = {
        type: Type.OBJECT,
        properties: {
          needsClarification: {
            type: Type.BOOLEAN,
            description: "True if the goal is too vague and needs a follow-up answer."
          },
          followupQuestion: {
            type: Type.STRING,
            description: "Encouraging, supportive follow-up question to clarify the user's goal if needsClarification is true."
          },
          goalPlan: {
            type: Type.OBJECT,
            description: "The full decomposed goal plan if needsClarification is false.",
            properties: {
              normalizedObjective: { type: Type.STRING },
              description: { type: Type.STRING },
              category: { type: Type.STRING },
              targetValue: { type: Type.NUMBER },
              unit: { type: Type.STRING },
              frequency: { type: Type.STRING },
              isRecurring: { type: Type.BOOLEAN },
              recurringDays: {
                type: Type.ARRAY,
                items: { type: Type.STRING },
              },
              color: { type: Type.STRING },
              icon: { type: Type.STRING },
              tasks: {
                type: Type.ARRAY,
                items: {
                  type: Type.OBJECT,
                  properties: {
                    title: { type: Type.STRING, description: "A tiny, achievable, specific action for this day on the roadmap" },
                    dayIndex: { type: Type.INTEGER, description: "Day index from 0 (Day 1) to 6 (Day 7)" },
                    value: { type: Type.NUMBER }
                  },
                  required: ["title", "dayIndex", "value"]
                }
              }
            },
            required: [
              "normalizedObjective", 
              "description", 
              "category", 
              "targetValue", 
              "unit", 
              "frequency", 
              "isRecurring", 
              "color", 
              "icon", 
              "tasks"
            ]
          }
        },
        required: ["needsClarification"]
      };

      const parsedResult = await generateContentWithGemini(ai, chatInput, systemPrompt, geminiResponseSchema);
      return res.json(parsedResult);
    } catch (geminiError: any) {
      console.log(`[AI Goal Coach] Native primary Gemini route failed (Reason: ${geminiError?.message || geminiError}). Seamlessly transferring payload to Anthropic backup...`);
    }
  } else {
    console.log("[AI Goal Coach] GEMINI_API_KEY environment variable is not defined or is placeholder. Attempting backup AI routing...");
  }

  // Backup pathway: Anthropic SDK
  if (hasAnthropicKey) {
    try {
      console.log("[AI Goal Coach] Triggering backup route via Anthropic SDK using ANTHROPIC_API_KEY...");
      const client = getAnthropicClient();
      const toolSchema = {
        type: "object",
        properties: {
          needsClarification: {
            type: "boolean",
            description: "True if the goal is too vague and needs a follow-up answer."
          },
          followupQuestion: {
            type: "string",
            description: "Encouraging, supportive follow-up question to clarify the user's goal if needsClarification is true."
          },
          goalPlan: {
            type: "object",
            description: "The full decomposed goal plan if needsClarification is false.",
            properties: {
              normalizedObjective: { type: "string" },
              description: { type: "string" },
              category: { type: "string" },
              targetValue: { type: "number" },
              unit: { type: "string" },
              frequency: { type: "string" },
              isRecurring: { type: "boolean" },
              recurringDays: {
                type: "array",
                items: { type: "string" },
              },
              color: { type: "string" },
              icon: { type: "string" },
              tasks: {
                type: "array",
                items: {
                  type: "object",
                  properties: {
                    title: { type: "string", description: "A tiny, achievable, specific action for this day on the roadmap" },
                    dayIndex: { type: "integer", description: "Day index from 0 (Day 1) to 6 (Day 7)" },
                    value: { type: "number" }
                  },
                  required: ["title", "dayIndex", "value"]
                }
              }
            },
            required: [
              "normalizedObjective", 
              "description", 
              "category", 
              "targetValue", 
              "unit", 
              "frequency", 
              "isRecurring", 
              "color", 
              "icon", 
              "tasks"
            ]
          }
        },
        required: ["needsClarification"]
      };

      const parsedResult = await generateContentWithRetry(client, chatInput, systemPrompt, toolSchema);
      return res.json(parsedResult);
    } catch (anthropicError: any) {
      console.log(`[AI Goal Coach] Backup Anthropic API failed (Reason: ${anthropicError?.message || anthropicError}). Seamlessly failing over to safe static engine...`);
    }
  }

  // Fallback: Safe Heuristic Engine (Ensures 100% service availability and instant execution under severe LLM outages)
  try {
    const fallbackResult = getHeuristicFallbackPlan(message);
    if (fallbackResult && fallbackResult.goalPlan) {
      let warningText = "[Coach Engine] Generated high-momentum action roadmap instantly: ";
      fallbackResult.goalPlan.description = warningText + fallbackResult.goalPlan.description;
      return res.json(fallbackResult);
    }
  } catch (fallbackError: any) {
    console.log("[AI Goal Coach] Heuristic fallback failure:", fallbackError);
  }

  return res.status(500).json({ error: "An unexpected decomposition fallback error occurred." });
});

// Heuristic fallback generator for Productivity analysis to support offline/local execution
function getHeuristicProductivityPlan(profileName: string, goalsListText: string) {
  return {
    encouragement: `Keep pushing forward, ${profileName || 'Achiever'}! Remember, your efforts are compound interest for your personal growth. Even if you missed a day, showing up to review your targets today is a huge victory!`,
    consistencyAdvice: `Make consistency easy by lowering boundaries. For your targets, schedule specific habit-stacking anchors. Connect each goal to an existing daily trigger (like morning routine or work wind-down) so you do not have to rely on active willpower.`,
    focusRecommendations: `Clear all focus distractions beforehand. Try working on your priorities using a single-tasking timer for just 15 minutes. Protect this focus block fiercely from notification prompts or tabs.`,
    recoverySuggestions: `Never miss twice! If you skipped a logging interval, do not worry about playing catchup. Simply execute a 'Micro-Habit' option (for example, reading just 1 page or doing a 2-minute stretch) to keep the habit spark alive.`
  };
}

// API endpoint to analyze current status and get personalized productivity advice
app.post("/api/coach/productivity", async (req, res) => {
  const { profile, goals } = req.body;
  
  const profileName = profile?.name || 'Achiever';
  const goalsCount = goals ? goals.length : 0;
  
  // Create a structured summary of the user's goals and logs to pass to the model
  let goalsSummary = "No goals set yet. Encourage the user to create their first goal/habit.";
  let missedDaysContext = "No history available.";

  if (goals && Array.isArray(goals) && goals.length > 0) {
    const todayStr = new Date().toISOString().split('T')[0];
    goalsSummary = goals.map((g: any, index: number) => {
      const logsCount = g.logs ? g.logs.length : 0;
      const currentVal = g.currentValue || 0;
      const targetVal = g.targetValue || 1;
      const unit = g.unit || 'times';
      const lastLog = logsCount > 0 ? g.logs[logsCount - 1] : null;
      let lastLogText = "never logged yet";
      if (lastLog) {
        lastLogText = `last value ${lastLog.value} on ${lastLog.date}`;
      }
      return `${index + 1}. "${g.title}" (${g.category}): Target is ${targetVal} ${unit}, current progress ${currentVal} ${unit}, logs count: ${logsCount}, ${lastLogText}.`;
    }).join("\n");

    // Analyze gaps or missed days (e.g. check if the last log date is in the past)
    const logDates = goals.flatMap((g: any) => (g.logs || []).map((l: any) => l.date));
    if (logDates.length > 0) {
      // Find latest logged date across all goals
      const sortedDates = [...new Set(logDates)].sort();
      const latestDateStr = sortedDates[sortedDates.length - 1];
      const latestLogDate = new Date(latestDateStr);
      const today = new Date();
      // Normalize to midnight UTC for distance checks
      today.setUTCHours(0,0,0,0);
      latestLogDate.setUTCHours(0,0,0,0);
      
      const diffMs = today.getTime() - latestLogDate.getTime();
      const diffDays = Math.floor(diffMs / (1000 * 60 * 60 * 24));
      
      if (diffDays > 1) {
        missedDaysContext = `The user last logged actions ${diffDays} days ago (on ${latestDateStr}). They have active missed days. Highlight gentle, concrete recovery advice specifically for this gap.`;
      } else {
        missedDaysContext = `The user is active! They last logged recently (on ${latestDateStr}). Praise their active streak and advise on maintaining standard consistency.`;
      }
    } else {
      missedDaysContext = `The user has created goals but hasn't logged any actions/values yet. Encourage them to make their very first quest log today.`;
    }
  }

  const systemPrompt = `You are Tracktion's Elite AI Productivity Coach. Your goal is to analyze the user's active goals and logging history to formulate an extremely personalized coaching advice report that covers four crucial dimensions:
1. CUSTOM ENCOURAGEMENT: Praise any positive streaks, logs, or simply congratulate them on taking control of their trajectory. Be highly supportive, energetic, and empathetic.
2. CONSISTENCY STRATEGY: Provide bespoke scheduling, habit-stacking, or identity-shifting consistency advice custom-fit to the user's goals.
3. DEEP FOCUS RECOMMENDATIONS: Share concrete methods to eliminate distractions, execute deep-focus blocks, reduce friction, or handle multitasking loops for their specific habits.
4. ACTIONABLE RECOVERY: Deliver comforting, pressure-free instructions on recovering momentum after a missed day or logging gap. Focus on micro-actions (e.g. 2-minute rule) to preserve psychological morale and sustain habit patterns.

Guidelines:
- Reference the user's actual goals by name (e.g., if they have a goal "Python study", reference "Python study").
- Match your tone to an intelligent, supportive mentor.
- Avoid generic filler. Keep each advice category highly actionable and specific to their active context.

Format requirements:
- Respond in JSON format matching the schema rules with exactly the properties: encouragement, consistencyAdvice, focusRecommendations, recoverySuggestions.`;

  const chatInput = `User Profile: Name is "${profileName}", Target Weekly Goals Count Goal is ${profile?.weeklyGoalCount || 3}.
Active Goals & Logs Summary:
${goalsSummary}

Missed Days & Timing Analysis:
${missedDaysContext}`;

  const geminiApiKey = process.env.GEMINI_API_KEY;
  const hasGeminiKey = geminiApiKey && geminiApiKey !== "MY_GEMINI_API_KEY";
  const anthropicApiKey = process.env.ANTHROPIC_API_KEY;
  const hasAnthropicKey = anthropicApiKey && anthropicApiKey !== "MY_ANTHROPIC_API_KEY";

  // 1. Try Google Gemini SDK
  if (hasGeminiKey) {
    try {
      console.log("[AI Productivity Coach] Querying native Google GenAI SDK...");
      const ai = getGeminiClient();

      const geminiResponseSchema = {
        type: Type.OBJECT,
        properties: {
          encouragement: { type: Type.STRING },
          consistencyAdvice: { type: Type.STRING },
          focusRecommendations: { type: Type.STRING },
          recoverySuggestions: { type: Type.STRING }
        },
        required: ["encouragement", "consistencyAdvice", "focusRecommendations", "recoverySuggestions"]
      };

      const parsedResult = await generateContentWithGemini(ai, chatInput, systemPrompt, geminiResponseSchema);
      return res.json(parsedResult);
    } catch (geminiError: any) {
      console.log(`[AI Productivity Coach] Gemini SDK failed (Reason: ${geminiError?.message || geminiError}). Falling back...`);
    }
  }

  // 2. Try Anthropic SDK
  if (hasAnthropicKey) {
    try {
      console.log("[AI Productivity Coach] Querying back-up Anthropic SDK...");
      const client = getAnthropicClient();
      const toolSchema = {
        type: "object",
        properties: {
          encouragement: { type: "string" },
          consistencyAdvice: { type: "string" },
          focusRecommendations: { type: "string" },
          recoverySuggestions: { type: "string" }
        },
        required: ["encouragement", "consistencyAdvice", "focusRecommendations", "recoverySuggestions"]
      };

      const parsedResult = await generateContentWithRetry(client, chatInput, systemPrompt, toolSchema);
      return res.json(parsedResult);
    } catch (anthropicError: any) {
      console.log(`[AI Productivity Coach] Backup Anthropic failed (Reason: ${anthropicError?.message || anthropicError}). Falling back to heuristics...`);
    }
  }

  // 3. Fallback to Heuristics
  try {
    const fallbackResult = getHeuristicProductivityPlan(profileName, goalsSummary);
    return res.json(fallbackResult);
  } catch (err) {
    console.log("[AI Productivity Coach] Critical fallback failure:", err);
  }

  return res.status(500).json({ error: "Could not generate productivity response at this time." });
});

// Serve static elements or hot development server routes
const startServer = async () => {
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on port ${PORT}`);
  });
};

startServer();
